version: '1.0'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: backend_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_challenge

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - backend_challenge

  server:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "backend_challenge"
      PORT: 3000
      MODE: DEV
      RUN_MIGRATIONS: true
      REDIS_URL: redis://redis:6379
    networks:
      - backend_challenge

volumes:
  postgres_data:

networks:
  backend_challenge:
